#!/bin/bash

set -e

R=https://source.developers.google.com/projects/ingress-barcodes/repos/barcodes/moveable-aliases/master/paths/

gcloud --project=ingress-barcodes functions deploy barcode \
	--source "$R" \
	--trigger-http --runtime=nodejs8

gcloud --project=ingress-barcodes functions deploy barcodemulti \
	--source "$R" \
	--trigger-http --runtime=nodejs8

gcloud --project=ingress-barcodes functions deploy help \
	--source "$R" \
	--trigger-http --runtime=nodejs8
